services:
  postgres:
    image: "postgres:${POSTGRES_VERSION:-14-alpine}"
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: "${POSTGRES_USER:-admin}"
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-admin}
    depends_on:
      localstack:
        condition: service_started

  localstack:
    image: localstack/localstack:2.2.0
    environment:
      #- DEBUG=1
      - DOCKER_HOST=unix:///var/run/docker.sock
      - LOCALSTACK_HOST=localhost
      - SERVICES=s3
    volumes:
      - .tmp/localstack:/var/lib/localstack
      - ./scripts/localstack-init.d/:/etc/localstack/init/ready.d/
      - /var/run/docker.sock:/var/run/docker.sock

    entrypoint: >
      bash -c "chmod 777 -R /tmp/localstack
      && /usr/local/bin/docker-entrypoint.sh"
    ports:
      - '4566:4566'
      - '4510-4559:4510-4559'

  #api:
  #  build:
  #    context: .
  #    dockerfile: Dockerfile

volumes:
  postgres-data:
