project:
  name: orion-api
  title: Orion API
  description: Povio Orion Nest.js Framework

~common/logger:
  # basic, pino, sentry, highlight
  provider: basic

dot-config:
  bootstrap: true

# AWS ECS Deploy Cli
ecs-deploy-cli:
  bootstrap: false
  mode: disabled
  #stages:
  #  - orion-api-dev

~database/prisma:
  mode: enabled
  autoMigrate: true

~common/http/openapi:
  # disabled, static, runtime
  mode: runtime
  # served on /docs-json
  path: docs

~common/email:
  mode: enabled
  # sendgrid, aws-ses
  provider: no-op

~common/queues:
  mode: enabled
  # pg-boss, hotwire
  provider: hotwire

~common/media:
  mode: enabled
  # aws-s3, prisma
  providers:
   - prisma

